### ISSUE TITLE
Error: TestMetacoin contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of TestMetacoin: ConvertLib

### ISSUE THREAD

**Issue by 7-of-9** [trufflesuite/truffle-box#14]
truffle unbox metacoin
truffle test

Yields error above, on integrated PowerShell in VS Code. Any help appreciated! My first foray into Solidity and Truffle. Full log:

PS C:\src\DAPP_TEST1\metacoin> truffle test
Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\contracts\Migrations.sol...
Compiling .\test\TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

  TestMetacoin
    1) "before all" hook: prepare suite

  Contract: MetaCoin
    √ should put 10000 MetaCoin in the first account
    √ should call a function that depends on a linked library (53ms)
    √ should send coin correctly (109ms)

  3 passing (586ms)
  1 failing

  1) TestMetacoin "before all" hook: prepare suite:
     Error: TestMetacoin contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of TestMetacoin: ConvertLib
      at C:\Users\dom\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:317824:17
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by 7-of-9** [comment]
Needed to stop geth --testnet and start "truffle develop".
